### ISSUE TITLE
[Loans] Catch up on adds and removes from nonzero list as soon as distributions complete.

### ISSUE THREAD

**Issue by dbrehmer** [balancednetwork/balanced-contracts#136]
Loans currently accumulates additions and removals from the nonzero list throughout the day and only catches up with them at the start of the next day in order to calculate the mining state for each position. It could cause trouble for the system if these lists get too long. To mitigate this it is suggested to only hold the changes to the nonzero list while the distributions are happening, which is when they need to be snapshotted for calculation of the mining state for all positions.

This concern is particularly notable for first day activity when the add_to_nonzero list could get very large as everyone joins. If there are removals from that list when it is large we could have failing transactions, but it probably would not happen if the number of additions is lower than 1000. Even then, in the worst case it would only cause transactions to fail if a person is paying off all of their debt. Other transactions would proceed just fine and the total payoff transaction would work the next day.

With this fix, changes to the nonzero list would only be cached during distributions and distributions will only be considered complete once the nonzero list has been brought up to date with those changes. Then changes during the rest of the day will be applied directly to the nonzero list.

**Comment by BennyOptions** [comment]
Might not need to do this if we convert to block-by-block rewards

**Comment by dbrehmer** [comment]
This will be made irrelevant when we remove the debt requirement for mining and rebalance over the entire borrower list.
