### ISSUE TITLE
Swap sICx for bnUSD

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-contracts#194]
Many users getting this error

https://tracker.icon.foundation/transaction/0x72943592225eb83793462b19505f1a85a28301a6c7b08467ee6ae0173ae4e21b

https://tracker.icon.foundation/transaction/0x36bb01a6fd7b1f2ae6e5b096c3063d3ecca1015376a792ce11712b31fd138ff5

**Comment by gedanziger** [comment]
Reassigning to @tuan-tl - it is likely a frontend issue

**Comment by gedanziger** [comment]
It appears the `minimumSlippage` param is submitted in an exponential format, particularly with a large purchase amount or an imbalanced pool. It should be sent as an integer format (1.2E+21 in exp format won't be accepted by the contract, it needs the full integer).
