### ISSUE TITLE
sICX Management SCORE: i-score is not getting claimed

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-contracts#202]
i-Score is accumulating but the SCORE is not claiming. It must claim, re-stake and delegate

**Comment by dbrehmer** [comment]
I-Score was claimed in the first txn after block 33690003, as Suyog suggested would happen. 8150.985597817543708636 ICX was received here - https://tracker.icon.foundation/transaction/0x4d264680eeb77443bb4bfc35fe07da871ab8ba75b1bf5c58e4dd7c2d44cedc3d#events
