### ISSUE TITLE
Change the fallback on Staking Management to forward to stakeICX method

### ISSUE THREAD

**Issue by dbrehmer** [balancednetwork/balanced-contracts#224]
Right now, if someone sends ICX to the staking contract it will accept it and give no sICX in return.

If we make the fallback invoke the stakeICX method there won't be a risk that users might do this and it would make minting sICX even easier.

Is there any unintended consequence to making this change?

**Comment by Suyog007** [comment]
> Right now, if someone sends ICX to the staking contract it will accept it and give no sICX in return.
> 
> If we make the fallback invoke the stakeICX method there won't be a risk that users might do this and it would make minting sICX even easier.
> 
> Is there any unintended consequence to making this change?

Yes we can do that. We shouldn't face any issue on that. We will need to provide param of stakeICX function **to** while sending ICX directly too.
