### ISSUE TITLE
[Loans] Change debt value & collateral value into USD rather than loop

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-contracts#266]

**Comment by BennyOptions** [comment]
This will make it easier when we add other collateral types and in order to calculate amount of rewards owed in real-time

**Comment by Deceivious** [comment]
Upon initial requirement analysis, we have found that this task requires changes  on snapshot which is complicated to implment as it deals with historical data storage. Continuous Rewards remove the need of snapshots reducing the scope and complexity of this task.

Commited all the work done so far in new branch "dev_loop_to_usd".

Any changes that needs to be reviewed in the future after the blocker has been cleared out have been marked with a todo: Bigya tag in the code.
