### ISSUE TITLE
Architecture: Retirements against the entire borrower set through a replayLog

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-contracts#275]

**Comment by BennyOptions** [comment]
Synthetix relevant contracts

State Contract
https://etherscan.io/address/0x4b9Ca5607f1fF8019c1C6A3c2f0CC8de622D5B82#readContract

Issuer Contract
https://etherscan.io/address/0xB774711F0BC1306ce892ef8C02D0476dCccB46B7#readContract

**Comment by BennyOptions** [comment]
Meeting notes:

- Using a non-transferable token to track users' debt positions could be helpful
- Their balance of this token / total supply of the token
- https://github.com/Synthetixio/synthetix/blob/master/contracts/SynthetixState.sol
- Their current solution is very brittle - moving toward the LP token model
- They can't update everybody's percentage of debt as new users leave/join
**- Perhaps the user could just own a share of the collateral pool rather than a specific amount - This was a breakthrough idea, should work**
- xSUSHI contract is a good one to look at (https://github.com/sushiswap/sushiswap/blob/canary/contracts/SushiBar.sol)

**Comment by BennyOptions** [comment]
This is seeming impossible, will likely icebox this and move to the replay log structure

**Comment by BennyOptions** [comment]
Let's move forward with ReplayLog structure after the initial implementation

**Comment by BennyOptions** [comment]
Let's have claiming BALN and claiming Network Fees act as driving transactions for replay logs

**Comment by dbrehmer** [comment]
Now our thinking is that batched rebalancing will work as well as replay logs and be simpler. It is only required that the percent rebalanced from each batch be small and equal, then all positions will be affected the same amount.
