### ISSUE TITLE
Governance: Refund the 100 bnUSD if the proposal is approved

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-contracts#283]
For a proposal that is approved, let's refund the 100 bnUSD to the proposer. This is a moderate incentive to do good proposals.

**Comment by BennyOptions** [comment]
@Skyvell please include this in your PR

**Comment by Skyvell** [comment]
Got it.

**Comment by BennyOptions** [comment]
Hopefully on main net 1 week from today
