### ISSUE TITLE
Community-Submitted Votes on Main net

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-contracts#314]
We need to allow the community to submit proposals on main net:

Qualifications:

- 100 bnUSD fee
- At least 0.1% of total BALN

Note: Remove the **"minimum"** of 5 days and make 5 days the requirement for voting period.

**Comment by Skyvell** [comment]
Noticed this. Should I exchange the minimum vote duration to a set vote duration? I assume this set vote duration should also be a settable gov parameter?

**Comment by BennyOptions** [comment]
Correct @Skyvell 

- minimum duration should just be a set duration
- yes, make duration settable as a gov parameter

**Comment by Skyvell** [comment]
Alright, will do.

**Comment by BennyOptions** [comment]
cancelVote - owner & EOA that submitted the vote available
activateVote -  remove this entirely

**Comment by BennyOptions** [comment]
Hopefully on main net 1 week from today

**Comment by Skyvell** [comment]
I see some problems with this Scott. I don't think it makes sense to keep only one of them. As it is now cancelVote can only cancel pendning votes, but if we remove activateVote, a vote needs to be activated in the definition process. The result is that the proposer can cancel a vote midvote. E.g. if the vote is on the verge of failing it could just be canceled and proposer gets refunded.

**Comment by Skyvell** [comment]
I kept both both for now. I'll write some more tests for the changes I just made then pass it on to a review. I think it's comming together now.

**Comment by Skyvell** [comment]
Hmm, I also think there is some merit to having this period between definition and activation. A user might want to get input from someone else to make sure everything is defined correctly before it's activated.
