### ISSUE TITLE
Governance: Set Actions in self.actions dictionary 

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-contracts#318]
We need to decide which methods will go here:

https://github.com/balancednetwork/balanced-contracts/blob/3f00d82d48b1d95374f592d6013ded7c986d8bc5/core_contracts/governance/data_objects.py#L33

List of methods:
https://docs.google.com/spreadsheets/d/1W__eUg8pS2_iQi5cEzZMzFg2rUMl11Q2vfjujhZkQUY/edit#gid=0

**Comment by BennyOptions** [comment]
Should be done by tonight

**Comment by simusud** [comment]
added actions in self.actions and have requested Dan for a review.
