### ISSUE TITLE
Smart Contract API Aggregator Contract

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-contracts#330]
Create an architecture where we have one contract that bundles many different APIs into one API call in order to send less queries to the blockchain.

Idea brought to us by @WeiLi512

**Comment by octocat512** [comment]
https://github.com/makerdao/multicall

**Comment by dbrehmer** [comment]
Aggregates multiple readonly APIs to simplify frontend calls to the endpoint.
