### ISSUE TITLE
Change actions to a list in the defineVote method

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-contracts#331]
We need to change how "actions" executes. If we want to execute multiple actions, dictionaries do not have a guaranteed order, so this could become a problem if order of actions matters.

**Comment by Skyvell** [comment]
@BennyOptions I think order in dictionary is guaranteed to be insertion order in python 3.7+.

**Comment by dbrehmer** [comment]
Thanks Ted. Good to know!
