### ISSUE TITLE
LP token style collateral pools

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-contracts#353]
We need to be able to support tokens that rebase, like oTokens

Methods effected:
- depositAndBorrow
- Liquidate

Change to the following method of collateral value calculation:
Information we need:
- Number of tokens in the pool
- LP token ratio - mine / supply
- tokenType
- Oracle price of respective token type

**Comment by BennyOptions** [comment]
The goal is to have a flexible architecture for adding new token types that could be staked versions of tokens, wrapped versions of tokens, tokens that have a rebase (oTokens), etc.

**Comment by BennyOptions** [comment]
Collateral accounting is more like liquidity pool accounting rather than account-based. We can essentially issue LP tokens for collateral types

**Comment by dbrehmer** [comment]
Assess whether we can wait on this. What would it cost us to implement this later?
