### ISSUE TITLE
Validate frontend transaction construction for vote types

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-contracts#372]
Please take a look at how the frontend is constructing "actions" to ensure that the frontend is building the transaction and submitting to the blockchain properly

BALN Allocation - https://bicon.tracker.solidwallet.io/transaction/0x9e25ca4d3b5db704818c8fcca9528f52f71db45e00081624a2449bb8ab061783

Network Fee Allocation - 
https://bicon.tracker.solidwallet.io/transaction/0x65cdedda6f576dd836d125c5069474d6cc3795be1e5c0f16a5cc1983673bf12f

Loan Fee - 
https://bicon.tracker.solidwallet.io/transaction/0xd7ff555936d169522d92b8789fcc156967cc898be8cfa10b7b871679e1d238c8

Loan to Value - 
https://bicon.tracker.solidwallet.io/transaction/0x1228f9adc949a4e328973f9cf8ce536649f0ed78ad1ae4f8898169f1fe651198

Rebalancing Threshold - 
https://bicon.tracker.solidwallet.io/transaction/0xd7a9f78b994ad0ab0bf1913fc29f459250764ff3404f4ddd96eb3755487bc069

**Comment by simusud** [comment]
In  Rebalancing Threshold actions:  "_value" is given as string , it must be an integer. 
Other looks good .

**Comment by BennyOptions** [comment]
Thank you @simusud, please also check the recently added daoDisburse action call

DAO Funding for 10,000 BALN -
https://bicon.tracker.solidwallet.io/transaction/0x574561aa2cb5bdb9bcdaad6013d174321947c9d28650ae88674858594629f084

**Comment by simusud** [comment]
daoDisburse action call looks good.

**Comment by BennyOptions** [comment]
Thank you, all are validated
