### ISSUE TITLE
Run test votes to make sure they can be enacted.

### ISSUE THREAD

**Issue by dbrehmer** [balancednetwork/balanced-contracts#421]
We have had a number of votes fail to enact. We need to test a couple that have not been tried in production yet.
Disbursements from the DAOfund
setDividendsCategoryPercentage

**Comment by simusud** [comment]
I have defined a vote for dao disburse in sejong and executed it. The status is Enacted.
https://test.balanced.network/vote/proposal/2

And claimed the tokens from the recipient address, it worked.

There is a bug in governance contract while checking vote action type whether it is dict or list. I have fixed the issue and created a PR. 

https://github.com/balancednetwork/balanced-contracts/pull/426

**Comment by simusud** [comment]
Also make sure dao fund score is updated in main net with the changes made in daoDisburse previously.

**Comment by dbrehmer** [comment]
Let's check off each of these vote types as they have been tested end to end

- [x]             'addNewDataSource': self._gov.addNewDataSource,
- [x]             'updateBalTokenDistPercentage': self._gov.internal_updateBalTokenDistPercentage,
- [x]             'setMiningRatio': self._gov.setMiningRatio,
- [x]             'setLockingRatio': self._gov.setLockingRatio,
- [x]             'setOriginationFee': self._gov.setOriginationFee,
- [x]             'setLiquidationRatio': self._gov.setLiquidationRatio,
- [x]             'setRetirementBonus': self._gov.setRetirementBonus,
- [x]             'setLiquidationReward': self._gov.setLiquidationReward,
- [x]             'setMaxRetirePercent': self._gov.setMaxRetirePercent,
- [x]             'setRebalancingThreshold': self._gov.setRebalancingThreshold,
- [x]             'setVoteDuration': self._gov.setVoteDuration,
- [x]             'setQuorum': self._gov.setQuorum,
- [x]             'setVoteDefinitionFee': self._gov.setVoteDefinitionFee,
- [x]             'setBalnVoteDefinitionCriterion': self._gov.setBalnVoteDefinitionCriterion,
- [x]             'setDividendsCategoryPercentage': self._gov.setDividendsCategoryPercentage,
- [x]             'daoDisburse': self._gov.daoDisburse,
- [x]             'addAcceptedTokens': self._gov.addAcceptedTokens

**Comment by simusud** [comment]
All the vote type has been tested .
