### ISSUE TITLE
Add resilient error handling to fee handler

### ISSUE THREAD

**Issue by dbrehmer** [balancednetwork/balanced-contracts#427]
Currently the whole app will break if the fee handler fails to process fees. We need it to fail gracefully and let the transactions continue, holding the fees to be dealt with later.

**Comment by Skyvell** [comment]
Got it. Could you eloborate on which features break? Only trading? I expect trading to break for those pairs that need, and do not have configured routes. Should go away when configured. Hopefully.

I'll make a PR for handling future cases (e.g. when a new pair is listed and not configured correctly in the fee handler and breaks trading for that particular pair).

**Comment by dbrehmer** [comment]
Yes, that's it. I'll check the PR soon. Thanks.
