### ISSUE TITLE
Create deployment starting state script

### ISSUE THREAD

**Issue by dbrehmer** [balancednetwork/balanced-contracts#431]
We need to be able to deploy the current mainnet starting state to test deployment for the router, fee handler and continuous rewards upgrades.

**Comment by simusud** [comment]
I have deployed a new environment which is equivalent to our current main net :
{"loans": "cx903637cfbc1c459a96c037efab67cf639b2877ea", "staking": "cxd28829b2d0f1391edb1ffc1ec46ac353db2ff4dd", "dividends": "cxdaa020d6fffb5da94d83faccc2a469a189ed2480", "reserve": "cxbb0c4c10c971e0dd3935ce270c6cfc2f878670db", "daofund": "cx65ecd947aca52f35f90f9559615d468f3ac1cde4", "rewards": "cxa885447965656de083f8b3b27e0372afbf5b3555", "dex": "cx481f7e10c7c4fc59d6ac68472018f10977a91b39", "rebalancing": "cx6f070006befbabe45bbd6c0b1ffa1f538a6bb009", "governance": "cx82d3a59eda11ce5540d2a1793633486711c8f6f2", "oracle": "cx0999df3af49a227fc8799f0d78d19cd8fe4bb76d", "sicx": "cxd5f4901712c93d846a454f861c579e54366953de", "bnUSD": "cx4428ab698443e62b88dc374f939c2fa251af6cd3", "bnXLM": "cx6c2b6c8dd300d5c96fc67a5617781de071b51159", "bnDOGE": "cx204a61990e3d7b9432b4b9da37bb9b8b83ec5f79", "baln": "cx1b0cb6da2d07be642eeebbdb0c5e3df248d4461b", "bwt": "cx598a1a4613e0790d35116421ef06038f0614ceee"}

**Comment by dbrehmer** [comment]
Will need to update this when feehandler and router are accepted.
