### ISSUE TITLE
Rebalancing Daily Limit

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-contracts#467]
Implement a daily limit on the amount of bnUSD that can be minted and burned through rebalancing. Not sure exactly how that number should be decided. Possible ideas:

- Percentage of total supply (perhaps 5%)
- Fixed number (perhaps 5,000,000)

Terra has a 100M maximum UST burn per day

**Comment by dbrehmer** [comment]
In discussion on forum.
